###  GAME  ###
FROM debian:latest AS game-builder

RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    libxcursor1 \
    libxrandr2 \
    libxinerama1 \
    libxi6 \
    libgl1 \
    libx11-6 \
    libxxf86vm1 \
    libxrender1 \
    libxfixes3 \
    libegl1 \
    xorg \
    xz-utils \
    xvfb \
    libxkbcommon-x11-0 \
    && rm -rf /var/lib/apt/lists/*

ARG GODOT_VERSION="4.4.1"
ARG GODOT_VERSION_TYPE="stable"
ARG GODOT_LINUX_URL="https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-${GODOT_VERSION_TYPE}/Godot_v${GODOT_VERSION}-${GODOT_VERSION_TYPE}_linux.x86_64.zip"
RUN wget -q ${GODOT_LINUX_URL} -O godot-headless.zip && \
    unzip godot-headless.zip && \
    mv Godot_v${GODOT_VERSION}-${GODOT_VERSION_TYPE}_linux.x86_64 /usr/local/bin/godot && \
    chmod +x /usr/local/bin/godot && \
    rm godot-headless.zip

ARG GODOT_TEMPLATES_URL="https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-${GODOT_VERSION_TYPE}/Godot_v${GODOT_VERSION}-${GODOT_VERSION_TYPE}_export_templates.tpz"
RUN mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.${GODOT_VERSION_TYPE} && \
    wget -q ${GODOT_TEMPLATES_URL} -O templates.tpz && \
    unzip templates.tpz && \
    mv templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.${GODOT_VERSION_TYPE}/ && \
    rm -rf templates templates.tpz


ARG DESIRED_BLENDER_VERSION="4.4"
ARG DESIRED_BLENDER_PATCH_VERSION="${DESIRED_BLENDER_VERSION}.3"
RUN wget -nv https://download.blender.org/release/Blender${DESIRED_BLENDER_VERSION}/blender-${DESIRED_BLENDER_PATCH_VERSION}-linux-x64.tar.xz && \
    tar -xJf ./blender-${DESIRED_BLENDER_PATCH_VERSION}-linux-x64.tar.xz && \
    mv ./blender-${DESIRED_BLENDER_PATCH_VERSION}-linux-x64 /opt/blender && \
    chmod +x /opt/blender/blender

WORKDIR /game
COPY game/ .

COPY game/editor_settings-4.4.tres.default /root/.config/godot/editor_settings-4.4.tres
RUN godot --headless --import

RUN mkdir dist
RUN godot --headless --export-release "Web" dist/index.html

### ADMIN UI ###
# FIXME: should be updated to :latest as soon as vite error is fixed there
FROM oven/bun:1.2 AS admin-builder
WORKDIR /admin
COPY admin/package.json admin/bun.lock ./
COPY admin/.env.example .env
RUN bun i --frozen-lockfile
COPY admin .
RUN bunx vite build

###  NGINX   ###
FROM nginx:alpine
COPY --from=game-builder /game/dist /usr/share/nginx/html/game
COPY --from=admin-builder /admin/dist /usr/share/nginx/html/admin
EXPOSE 80
