// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

import { Vector3 as __Vector3 } from "./vector_3_type";

export type SetUserData = {
  position: __Vector3,
  rotation: __Vector3,
  linearVelocity: __Vector3,
  angularVelocity: __Vector3,
  isActive: boolean,
  trackId: bigint,
  carId: bigint,
};

/**
 * A namespace for generated helper functions.
 */
export namespace SetUserData {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("position", __Vector3.getTypeScriptAlgebraicType()),
      new ProductTypeElement("rotation", __Vector3.getTypeScriptAlgebraicType()),
      new ProductTypeElement("linearVelocity", __Vector3.getTypeScriptAlgebraicType()),
      new ProductTypeElement("angularVelocity", __Vector3.getTypeScriptAlgebraicType()),
      new ProductTypeElement("isActive", AlgebraicType.createBoolType()),
      new ProductTypeElement("trackId", AlgebraicType.createU64Type()),
      new ProductTypeElement("carId", AlgebraicType.createU64Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: SetUserData): void {
    SetUserData.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): SetUserData {
    return SetUserData.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

