// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

// Import and reexport all reducer arg types
import { ClientConnected } from "./client_connected_reducer.ts";
export { ClientConnected };
import { IdentityDisconnected } from "./identity_disconnected_reducer.ts";
export { IdentityDisconnected };
import { SetName } from "./set_name_reducer.ts";
export { SetName };
import { SetUserData } from "./set_user_data_reducer.ts";
export { SetUserData };
import { UpdatePersonalBest } from "./update_personal_best_reducer.ts";
export { UpdatePersonalBest };

// Import and reexport all table handle types
import { PersonalBestTableHandle } from "./personal_best_table.ts";
export { PersonalBestTableHandle };
import { UserTableHandle } from "./user_table.ts";
export { UserTableHandle };
import { UserDataTableHandle } from "./user_data_table.ts";
export { UserDataTableHandle };

// Import and reexport all types
import { PersonalBest } from "./personal_best_type.ts";
export { PersonalBest };
import { User } from "./user_type.ts";
export { User };
import { UserData } from "./user_data_type.ts";
export { UserData };
import { Vector3 } from "./vector_3_type.ts";
export { Vector3 };

const REMOTE_MODULE = {
  tables: {
    personal_best: {
      tableName: "personal_best",
      rowType: PersonalBest.getTypeScriptAlgebraicType(),
      primaryKey: "id",
    },
    user: {
      tableName: "user",
      rowType: User.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
    },
    user_data: {
      tableName: "user_data",
      rowType: UserData.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
    },
  },
  reducers: {
    client_connected: {
      reducerName: "client_connected",
      argsType: ClientConnected.getTypeScriptAlgebraicType(),
    },
    identity_disconnected: {
      reducerName: "identity_disconnected",
      argsType: IdentityDisconnected.getTypeScriptAlgebraicType(),
    },
    set_name: {
      reducerName: "set_name",
      argsType: SetName.getTypeScriptAlgebraicType(),
    },
    set_user_data: {
      reducerName: "set_user_data",
      argsType: SetUserData.getTypeScriptAlgebraicType(),
    },
    update_personal_best: {
      reducerName: "update_personal_best",
      argsType: UpdatePersonalBest.getTypeScriptAlgebraicType(),
    },
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "ClientConnected", args: ClientConnected }
| { name: "IdentityDisconnected", args: IdentityDisconnected }
| { name: "SetName", args: SetName }
| { name: "SetUserData", args: SetUserData }
| { name: "UpdatePersonalBest", args: UpdatePersonalBest }
;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  onClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("client_connected", callback);
  }

  removeOnClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("client_connected", callback);
  }

  onIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("identity_disconnected", callback);
  }

  removeOnIdentityDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("identity_disconnected", callback);
  }

  setName(name: string) {
    const __args = { name };
    let __writer = new BinaryWriter(1024);
    SetName.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_name", __argsBuffer, this.setCallReducerFlags.setNameFlags);
  }

  onSetName(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.onReducer("set_name", callback);
  }

  removeOnSetName(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.offReducer("set_name", callback);
  }

  setUserData(position: Vector3, rotation: Vector3, linearVelocity: Vector3, angularVelocity: Vector3, isActive: boolean, trackId: number) {
    const __args = { position, rotation, linearVelocity, angularVelocity, isActive, trackId };
    let __writer = new BinaryWriter(1024);
    SetUserData.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_user_data", __argsBuffer, this.setCallReducerFlags.setUserDataFlags);
  }

  onSetUserData(callback: (ctx: ReducerEventContext, position: Vector3, rotation: Vector3, linearVelocity: Vector3, angularVelocity: Vector3, isActive: boolean, trackId: number) => void) {
    this.connection.onReducer("set_user_data", callback);
  }

  removeOnSetUserData(callback: (ctx: ReducerEventContext, position: Vector3, rotation: Vector3, linearVelocity: Vector3, angularVelocity: Vector3, isActive: boolean, trackId: number) => void) {
    this.connection.offReducer("set_user_data", callback);
  }

  updatePersonalBest(trackId: bigint, time: bigint, checkpointTimes: bigint[]) {
    const __args = { trackId, time, checkpointTimes };
    let __writer = new BinaryWriter(1024);
    UpdatePersonalBest.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_personal_best", __argsBuffer, this.setCallReducerFlags.updatePersonalBestFlags);
  }

  onUpdatePersonalBest(callback: (ctx: ReducerEventContext, trackId: bigint, time: bigint, checkpointTimes: bigint[]) => void) {
    this.connection.onReducer("update_personal_best", callback);
  }

  removeOnUpdatePersonalBest(callback: (ctx: ReducerEventContext, trackId: bigint, time: bigint, checkpointTimes: bigint[]) => void) {
    this.connection.offReducer("update_personal_best", callback);
  }

}

export class SetReducerFlags {
  setNameFlags: CallReducerFlags = 'FullUpdate';
  setName(flags: CallReducerFlags) {
    this.setNameFlags = flags;
  }

  setUserDataFlags: CallReducerFlags = 'FullUpdate';
  setUserData(flags: CallReducerFlags) {
    this.setUserDataFlags = flags;
  }

  updatePersonalBestFlags: CallReducerFlags = 'FullUpdate';
  updatePersonalBest(flags: CallReducerFlags) {
    this.updatePersonalBestFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get personalBest(): PersonalBestTableHandle {
    return new PersonalBestTableHandle(this.connection.clientCache.getOrCreateTable<PersonalBest>(REMOTE_MODULE.tables.personal_best));
  }

  get user(): UserTableHandle {
    return new UserTableHandle(this.connection.clientCache.getOrCreateTable<User>(REMOTE_MODULE.tables.user));
  }

  get userData(): UserDataTableHandle {
    return new UserDataTableHandle(this.connection.clientCache.getOrCreateTable<UserData>(REMOTE_MODULE.tables.user_data));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
