name: Build and Publish Docker Images

on:
    push:
        tags:
            - '*'

jobs:
    web:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to ghcr
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  context: .
                  file: Dockerfile.web
                  tags: ghcr.io/legendariusx/turboflop-web:latest

    spacetime:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to ghcr
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  context: server
                  file: server/Dockerfile.spacetime
                  tags: ghcr.io/legendariusx/turboflop-spacetime:latest
